# Generated by Django 5.0.1 on 2025-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
