# Generated by Django 5.0.1 on 2025-05-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='static/api/images/DefaultProfilePicAlt.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
