# Generated by Django 5.0.1 on 2025-05-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='default/DefaultProfilePicAlt.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
