# Generated by Django 5.0.1 on 2025-03-19 16:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_comment_id_alter_comment_post_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/', validators=[api.models.validate_file]),
        ),
    ]
