name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: artmedia
          POSTGRES_USER: artuser
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U artuser -d artmedia"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

        # Just build the images to check for errors without running them (cause then they may run forever)
      - name: Build Angular image
        run: docker build -t angular-app ./ArtMediaSite

      - name: Build Django image
        run: docker build -t django-app ./ArtMediaAPI