name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run
        run: |
          docker compose up -d --build

      - name: Health check (Django)
        run: curl --fail http://localhost:8000/ || exit 1

      - name: Health check (Angular)
        run: curl --fail http://localhost:4200/ || exit 1

      - name: Shut down
        if: always()
        run: docker compose down

