name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

        # Just build the images to check for errors wuthout running them (cause then they may run forever)
      - name: Build Angular image
        run: docker build -t angular-app ./ArtMediaSite

      - name: Build Django image
        run: docker build -t django-app ./ArtMediaAPI